name: Araiz Condoy
favicon: null
layout_spectrum: 0
typography_spectrum: 0.55738
title: Araiz Condoy Prouctions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#fafbea'
    - '#b86d36'
    - '#c4c3b8'
    - '#666535'
  brandStrength: 0.1875
  lightness: 0.875
  saturation: 1
  rhythmicContrast: 1
purpose: []
