name: Araiz Condoy
favicon: null
layout_spectrum: 0.99822
typography_spectrum: 0.55738
title: Araiz Condoy Productions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3f606f'
    - '#92aa9d'
    - '#d2dbbe'
    - '#fcfff6'
    - '#193340'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
